### PR TITLE
Update CalC.java

### PR DESCRIPTION
**Pull request by SOH28**
hey I have made it but it has got one issue....when u press any operand the display number gets converted into double format
Ex: I want to make a calc 5x6. When I press x operand the display shows 5.00x6

### CODE REVIEW

**Review by abirbhattacharya82 — COMMENTED** [review]
Its not properly functioning. Try press 76X, it will show 6.0X.

**Comment by SOH28** [comment]
I made such a big silly mistake😂😛 and I am extremely sry about that.....I fixed it bro!
Pls mark the change.....!

**Review by abirbhattacharya82 — APPROVED** [review]
Great Job. Thank you For Contributing..

**Comment by SOH28** [comment]
hey bro....I found another bug....I am trying my best to solve it...you also try
when u put decimal number at first it changes the value to some other value
Ex: 1.36X(next value) it display shows: (diff value)X(next value)
But the second calc  the decimal values works well

**Comment by abirbhattacharya82** [comment]
Do one thing then. Create an issue about it and then fix it. It will be easy keep track. Thank you for looking into it.

**Pull request merged**
